# 0.1.5.1: .catch, Promise.all

## Learning Objectives

1. `.catch` allows us to run specified logic when our programs encounter errors in promises
2. `Promise.all` allows us to wait on multiple promises concurrently instead of sequentially

## `.catch`

`.catch` allows us to run specified logic when our programs encounter errors in promises. For example, if our program runs a database query and the database is unreachable, we can program logic to return a graceful error message in the `.catch` block.

```javascript
// client is a Client instance from the Node pg library
client
  // .query returns a promise
  .query("SELECT * from recipes WHERE category=vegan")
  .then((recipes) => {
    // Render the lovely vegan recipes
  })
  // The .catch block will trigger on error in either .query or .then block
  .catch((error) => {
    console.error(error);
    // Handle the error gracefully, e.g. render 404 page instead of crashing app
  })
```

## `Promise.all`

`Promise.all` allows us to wait on multiple promises concurrently instead of sequentially. For example, if I wanted to retrieve independent data to render on a page in an app such as recipes, categories and users, I could use `Promise.all` to wait for multiple database queries to all return before proceeding. Without `Promise.all` we would need to wait for each of these queries sequentially using `.then`.

```javascript
const results = Promise.all([
  pool.query("SELECT * FROM recipes"),
  pool.query("SELECT * FROM categories"),
  pool.query("SELECT * FROM users"),
  // results is an array of results whose elements correspond
  // to the elements in the Promise.all parameter array
]).then((results) => {
  const [recipes, categories, users] = results;
  // Do something with recipes, categories and users
});
```
